APP_ALIASES = {
    "google chrome": "chrome.exe",
    "microsoft edge": "msedge.exe",
    "microsoft word": "C:\\Program Files\\Microsoft Office\\Office16\\WINWORD.EXE",
    "microsoft excel": "C:\\Program Files\\Microsoft Office\\Office16\\EXCEL.EXE",
    "notepad": "notepad.exe",
    "calculator": "calc.exe",
    "command prompt": "cmd.exe",
    "notepad": "notepad.exe",
    "calculator": "calc.exe",
    "paint": "mspaint.exe",
    "word": "winword.exe",
    "excel": "excel.exe",
    "powerpoint": "powerpnt.exe",
    "chrome": "chrome.exe",
    "firefox": "firefox.exe",
    "edge": "msedge.exe",
    "vscode": "code.exe",
}